name: app_forma_lite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  supabase_flutter: ^2.3.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  freezed_annotation: ^2.4.1
  flutter_markdown: ^0.6.17
  intl: ^0.19.0
  json_annotation: ^4.9.0
  ffmpeg_kit_flutter: ^5.1.0
  flutter_local_notifications: ^17.1.2
  clock: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.1
  path_provider_platform_interface: ^2.1.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/shaders/
    - assets/sfx/
    - assets/ambient/
