name: Build-Android
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
      - run: cd app && flutter pub get
      - run: cd app && flutter build apk --release
