name: Test
on: [pull_request]
jobs:
  analyze_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: "3.22.0" }
      - run: cd app && flutter pub get
      - run: cd app && flutter analyze --fatal-infos
      - run: cd app && flutter test
  supabase_migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - run: supabase db diff --project-ref ${{ secrets.SUPABASE_REF }}
